version: '3.8'

services:
  app-backend:
    image: ghcr.io/felipevitor/tcc-backend-api:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "8080:8000"
    volumes:
      - .:/app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 15
