app = "backend-tcc-livraria-virtual"

[build]
  dockerfile = "./Dockerfile"

[env]
  DATABASE_URL = "postgres://<usuario>:<senha>@<host>:<port>/<database>"

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Adicione esta seção de rootfs
[experimental]
  rootfs = "rootfs"
