version: '3.8'

services:
  app-backend:
    image: ghcr.io/felipevitor/tcc-backend-api:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "9000:8000"
    restart: unless-stopped

  app-frontend:
    image: ghcr.io/felipevitor/tcc-frontend:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "7000:80"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://198.7.113.9:9000/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 20
