version: '3.8'

services:
  app-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    restart: unless-stopped

  app-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "7000:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
